version: '3.3'

services:

    cloudsoft-amp:
        image: eu.gcr.io/gemalto-hackathon/cloudsoft/amp:latest
        ports:
          - "8081:8081"
        volumes:
          - ./docker/amp/etc/brooklyn.cfg:/etc/amp/brooklyn.cfg
          - ./docker/amp/ssh/:/home/amp/.ssh/
          - ./docker/amp/persisted-state/:/var/lib/amp/
          - ./docker/amp/log/:/opt/amp/data/log/
    dpod-ui:
        depends_on:
          - cloudsoft-amp
        image: eu.gcr.io/gemalto-hackathon/cloudsoft/dpod-ui:latest
        environment:
            UAA_URL: https://xxxxxxxx.uaa.system.mayfly.dpsas.io
            API_URL: https://xxxxxxxx.market.staging-dpondemand.io
            AMP_URL: http://cloudsoft-amp:8081
            AMP_AUTH: admin:password
        ports:
          - "8080:80"

